### PR TITLE
New version warning fixes

### LINKED ISSUE #13: [IMPORTANT] keframe needs fix to work on Flutter 3.0.0
## Steps to Reproduce

Just update your flutter to latest 3.0.0 release

## Actual results

```
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/keframe-2.0.6/lib/src/frame_separate_task.dart:43:63: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        priority: entry.priority, scheduler: SchedulerBinding.instance!)) {
                                                              ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/keframe-2.0.6/lib/src/frame_separate_task.dart:89:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    await SchedulerBinding.instance!.endOfFrame;
                           ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/keframe-2.0.6/lib/src/frame_separate_widget.dart:71:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/D:/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((Duration t) {
                     ^
```

### PR DESCRIPTION
**Pull request by viralkachhadiya**
Flutter New Version 3.0.0 warning fixes  #13

### CODE REVIEW

**Review by arxdeus — APPROVED** [review]

**Comment by arxdeus** [comment]
@Nayuta403 merge it for fix warnings

**Comment by Nayuta403** [comment]
Thanks PR, users who do not use 3.0 May report an error if it is modified like this, do you need to add SDK version limit

**Comment by viralkachhadiya** [comment]
Oh, i forgot it. I am adding.

**Comment by Nayuta403** [comment]
I create a new branch @viralkachhadiya  https://github.com/LianjiaTech/keframe/tree/master-3.0.
You can submit it here, and I'll release a version in this branch. When 3.0 is used more, merge into Master

**Comment by viralkachhadiya** [comment]
Okay

**Comment by viralkachhadiya** [comment]
@Nayuta403  is it good? i submitted my pr to your new branch master-3.0.

**Pull request merged**
